name: Test Runner

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest   # теперь GitHub-hosted runner
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello from GitHub-hosted runner!"
