name: Test Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
<<<<<<< HEAD
  build:
    runs-on: self-hosted
=======
  test:
    runs-on: ubuntu-latest   # теперь GitHub-hosted runner
>>>>>>> dc0f0150af94dd310808228b0cc58fa91a835c2d
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

<<<<<<< HEAD
      - name: Print message
        run: echo "Hello from self-hosted runner!"
=======
      - name: Say Hello
        run: echo "Hello from GitHub-hosted runner!"
>>>>>>> dc0f0150af94dd310808228b0cc58fa91a835c2d
